services:
  lv8girl:
    container_name: lv8girl
    image: ghcr.io/mchappyfriskyo/lv8girl:main
    ports:
      - 127.0.0.1:60009:80
    depends_on:
      - db
    volumes:
      - ./data:/var/www/html/uploads
  db:
    container_name: lv8girl-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: KQ9Yiq2devoxQxTvjuntLF
      MYSQL_DATABASE: lv8girl
      MYSQL_USER: lv8girl
      MYSQL_PASSWORD: yourpasswd
    volumes:
      - ./db:/var/lib/mysql
